version: "3"

services: 
    
    app:
        container_name: ${APP_NAME}
        build: 
            context: ./
            args: 
                - APP_PATH=${APP_PATH}
                - NODE_VERSION=${NODE_VERSION}
                - EXPOSE_PORT=${EXPOSE_PORT}
        ports: 
            - "${LOCAL_PORT}:${EXPOSE_PORT}"
        volumes: 
            - ${APP_PATH}:/usr/src/app
        command: ${NPM_COMMAND}