version: "3"

services: 
    
    app:
        container_name: ${APP_NAME}
        build: 
            context: ./
            args: 
                - NODE_VERSION=${NODE_VERSION}
                - EXPOSE_PORT=${EXPOSE_PORT}
        ports: 
            - "${LOCAL_PORT}:${EXPOSE_PORT}"
        volumes: 
            - ./app:/usr/src/app